### ISSUE TITLE
Occasional 503 error response from API server

### ISSUE THREAD

**Issue by malcolmang** [AY2223S1-CS2113-T17-4/tp#11]
The API sometimes returns the following json string `{"fault":{"faultstring":"Execution of ServiceCallout Service-Callout-Validate-Account-Key failed. Reason: ResponseCode 503 is treated as error","detail":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}`. This doesn't trigger a correct exception as the file is successfully written to, but still results in an invalid json file that cannot be loaded.

This may be due to rate-limiting and too-frequent calls, but it happens randomly and we are so far unable to reproduce this error. FYI @pipipipi2002

**Comment by pipipipi2002** [comment]
ResponseCode 503 is linked to "the server is not ready to handle the request", will implement error handler for this.

**Comment by pipipipi2002** [comment]
Closed with PR: #38
