### ISSUE TITLE
LTA API limited to 500 responses per request

### ISSUE THREAD

**Issue by malcolmang** [AY2223S1-CS2113-T17-4/tp#13]
Currently the LTA API supports only up to 500 responses per API call, and the program only calls once, so we are only limited to getting the first 500 carparks off the API. We will need to follow the procedure as below to get the fully formed json:

![image](https://user-images.githubusercontent.com/42490384/194735065-669fe4af-bd8b-4160-93be-48e5c5414977.png)

FYI @pipipipi2002

**Comment by pipipipi2002** [comment]
closed with #90
