### ISSUE TITLE
[PE-D][Tester C] Table not loading

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-T17-4/tp#140]
Table is not loading properly

![Screenshot from 2022-10-28 16-55-00.png](https://raw.githubusercontent.com/snuckerzlol/ped/main/files/e248a06c-bd7d-434e-a8db-2d3741cf7018.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: snuckerzlol/ped#1

**Comment by pipipipi2002** [comment]
closed with #165
