### ISSUE TITLE
[PE-D][Tester D] List feature suggestion

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-T17-4/tp#141]
List commands outputs many many lines of results that is jumbled up (not in any order)

Would be better if it was stored alphabetically / some form so it would be easier to see the results.

It is hard to scroll through everything.

Screenshot:

![image.png](https://raw.githubusercontent.com/wangtingjia/ped/main/files/07b7b72e-d024-4e80-8150-571ec7445098.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: wangtingjia/ped#2

**Comment by malcolmang** [comment]
Closed with https://github.com/AY2223S1-CS2113-T17-4/tp/pull/169: feature implemented
