### ISSUE TITLE
[PE-D][Tester C] Too many parking lot

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-T17-4/tp#143]
As a user I don't want to see all of the parking lots that fill up the screen

![Screenshot from 2022-10-28 17-01-43.png](https://raw.githubusercontent.com/snuckerzlol/ped/main/files/a20d216d-ac91-4cfc-b4db-737f3cdb4c9f.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: snuckerzlol/ped#3

**Comment by pipipipi2002** [comment]
I think this is a valid issue but it is what the command is supposed to do. That is why we have another command such as find and filter command right.
