### ISSUE TITLE
[PE-D][Tester A] [Bug] Could not filter for carpark ID

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-T17-4/tp#145]
![image.png](https://raw.githubusercontent.com/chinhan99/ped/main/files/8ff2e1e9-09cd-429a-a07d-7f84e6d4034f.png)

Was unable to filter for carpark ID. Is there a way to add support for filtering out carpark ID in addition to filtering out the location keywords? Sometimes user may just type in the 4-5 digit ID which is easier to search compared to typing location keywords.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: chinhan99/ped#2

**Comment by pipipipi2002** [comment]
filter command can support search by both ID and Address using flags.

**Comment by malcolmang** [comment]
Enabled support with https://github.com/AY2223S1-CS2113-T17-4/tp/pull/169. Integration with parser still needed
