### ISSUE TITLE
[PE-D][Tester C] Find typo

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-T17-4/tp#149]
Find not working if I added things with space
![Screenshot from 2022-10-28 17-20-28.png](https://raw.githubusercontent.com/snuckerzlol/ped/main/files/08c7a135-3e68-46a9-80b0-692eff09fdd9.png)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: snuckerzlol/ped#7

**Comment by malcolmang** [comment]
Closed with https://github.com/AY2223S1-CS2113-T17-4/tp/pull/163
