### ISSUE TITLE
[PE-D][Tester C] Update command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-T17-4/tp#152]
Is the update not done automatically?

![Screenshot from 2022-10-28 17-22-50.png](https://raw.githubusercontent.com/snuckerzlol/ped/main/files/d5e22405-ca90-4192-9352-80442003461c.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: snuckerzlol/ped#8

**Comment by pipipipi2002** [comment]
Closed with #161
