### ISSUE TITLE
Make authenticate able to determine if API key is valid

### ISSUE THREAD

**Issue by kyrenechua** [AY2223S1-CS2113-T17-4/tp#56]
Current AUTH just pushes input into secret.txt. Now add a feature for auth to determine if api key is valid or not

**Comment by pipipipi2002** [comment]
Support added with #70 
@kyrenechua check parking file. Make sure to input api string into my auth function not the whole user input (with the command). Dont initialise an API class inside the auth command class also since my api instance keeps the current api key as a variable
