### ISSUE TITLE
Jar Initialisation unintended effect

### ISSUE THREAD

**Issue by pipipipi2002** [AY2223S1-CS2113-T17-4/tp#66]
<img width="758" alt="Screen Shot 2022-10-13 at 16 48 36" src="https://user-images.githubusercontent.com/65348889/195549242-69d35891-b402-41ce-894e-f441744aaabb.png">
No backup data found when we use the jar file. @malcolmang

**Comment by pipipipi2002** [comment]
We need to populate the secret.txt file with a default api key instead of keeping it in a variable. This is so that the loading of key will be as expected. @pipipipi2002 

Need to update the initialisation part also, if no text found, we tell them we create the data file, and populate with the default API key. They are free to change using the auth command

**Comment by malcolmang** [comment]
Fixed as of https://github.com/AY2223S1-CS2113-T17-4/tp/pull/88
